fix: remove `@types/eslint__js`
This package causes a TypeScript compilation error for some reason...

```
error TS2688: Cannot find type definition file for 'eslint__js'.
  The file is in the program because:
    Entry point for implicit type library 'eslint__js'
```

However, `@eslint/js` provides its own types now, so we don't need this anymore.